- name: variables from files
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Course duration is {{Duration}}"